version: '3'
services:
  object-detector-image-web-assembly:
    # command: ['sh', 'docker-entrypoint.sh']
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - app-unison-sync:/home/docker/apps:nocopy

volumes:
  app-unison-sync:
    external:
      name: ${COMPOSE_PROJECT_NAME}-unison-sync